# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61dab8a03ea7449473ed4938eea4451c9443dc01b586d6b12bb0704c4cac8766b6cf87a21a976035f51bf4018f8772e5251352485f91921b649d5330cd4b438e

test:
  secret_key_base: 3f046a560ca6c7869992b216d95cafe8512c464efbb388a9c9820d90d3e1e992cffb78b825fd4eacadf661d6f24c970b47fcec3ccdf795721a5dbd791841340f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
